version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'blogdb'
      MYSQL_ROOT_PASSWORD: 'pa55word'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    environment:
      - NODE_ENV=development
      - DB_NAME=blogdb
      - DB_USERNAME=root
      - DB_PASSWORD=pa55word
      - DB_HOST=db
      - DB_PORT=3306
      - DB_SSL=false
      - BASE_URL=http://localhost:3000
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  mysql_data:
