FROM node:19-alpine

ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG PORT

ENV DB_NAME=$DB_NAME
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV PORT=$PORT

WORKDIR /app
COPY . .
RUN npm install
EXPOSE 3000

CMD [ "npm", "start" ]